import type { Player, PlayerAttribute, TacticalPlan, TrainingBlock, TrainingIntensity, TrainingQualityLabel } from './models'
import { tacticalFamiliarity } from '../data/mockData'
import { calculateTrainingStaffImpact } from './staff'
import type { StaffPerson } from './staff'
import { FULL_SESSION_BLOCKS } from './training'
import { PERSONALITY_MODIFIERS, selectPersonalityForAge } from './trainingPersonality'
import { POSITION_RATING_WEIGHTS, POSITION_TO_RATING_PROFILE } from './playerRatings'
import { TRAINABLE_ATTRIBUTES, TRAINING_BALANCE, ageFactor, clamp20, clamp100, consolidationDifficulty, continuityFactor, provisionalDifficulty } from './trainingBalance'
import type { AttributeTrainingState, FamiliarityMemory, FunctionalTrainingSession, TacticalFamiliarityState, TrainingGameState, TrainingPlayerState } from './trainingTypes'
import { getConditionLabel, getFamiliarityLabel, getFatigueLabel } from './humanState'
import { applyPhysicalIssueToAttributes, applyTrainingLoadToIssue, generateInitialPhysicalIssues, getPhysicalIssueEffects } from './physicalIssues'

const PHYSICAL_ATTRIBUTES: PlayerAttribute[] = ['rapidez', 'fuerza', 'resistencia', 'agilidad']
const instructionKeys = ['mentality', 'passingStyle', 'tempo', 'afterRecovery', 'pressingHeight', 'pressingIntensity', 'afterLoss'] as const
const planValue = (plan: TacticalPlan, key: string) => String(plan[key as keyof TacticalPlan])
const memory = (value: number): FamiliarityMemory => ({ current: value, historicalMax: value, trainedThisWeek: false })
const clone = <T,>(value: T): T => structuredClone(value)
function nextRandom(seed: number) { const next = (Math.imul(1664525, seed >>> 0) + 1013904223) >>> 0; return [next / 4294967296, next] as const }
function randomRange(state: TrainingGameState, minimum: number, maximum: number) { const [value, seed] = nextRandom(state.seed); state.seed = seed; return minimum + value * (maximum - minimum) }
const mean = (values: number[]) => values.reduce((sum, value) => sum + value, 0) / Math.max(1, values.length)
const actualBlocks = (session: FunctionalTrainingSession) => FULL_SESSION_BLOCKS.includes(session.blocks[0]) ? [session.blocks[0]] : session.blocks

const initialPhysicalValue = (seed: number, playerId: number, salt: number) => Math.imul((seed ^ salt) + playerId * 374761393, 668265263) >>> 0

export function createInitialTrainingState(players: Player[], seed = 84731): TrainingGameState {
  const instructions = Object.fromEntries(Object.entries(tacticalFamiliarity.instructions).map(([key, values]) => [key, Object.fromEntries(Object.entries(values).map(([option, value]) => [option, memory(value)]))]))
  const formations = Object.fromEntries(Object.entries(tacticalFamiliarity.formation).map(([key, value]) => [key, memory(value)]))
  const playerStates = Object.fromEntries(players.map((player) => [player.id, {
    playerId: player.id, baseAttributes: { ...player.attributes }, attributes: {}, fitness: 36 + initialPhysicalValue(seed, player.id, 0x9e3779b9) % 41,
    fatigue: 3 + initialPhysicalValue(seed, player.id, 0x85ebca6b) % 9, personality: selectPersonalityForAge(player.age, initialPhysicalValue(seed, player.id, 0xc2b2ae35)),
    happiness: { teammates: clamp100(player.happiness + 2), playingTime: clamp100(50 + player.appearances * 8), training: player.happiness, results: 62 },
    managerRelationship: clamp100(52 + ((player.id * 11) % 21)),
    managerAuthority: clamp100(56 + ((player.id * 7) % 17)),
    lockerRoomInfluence: player.traits.includes('VETERANO') ? 'LEADER' : player.id % 5 === 0 ? 'HIGH' : player.id % 3 === 0 ? 'MEDIUM' : 'LOW',
  } satisfies TrainingPlayerState]))
  return { week: 1, seed, players: generateInitialPhysicalIssues(playerStates, seed, '2026-08-25T18:00:00'), familiarity: { instructions, formations, setPieces: memory(54), setPieceWeeksWithoutTraining: 0 }, sessions: [
    { id: 'tuesday', day: 'Martes', intensity: 'Media', blocks: ['Físico', 'Transición ofensiva'], status: 'pending', planningStatus: 'UNPLANNED', attendance: 16, totalPlayers: players.length, absentPlayerIds: [4, 12, 20, 15], plannedAbsentPlayerIds: [4, 12, 20, 15], plannedAbsenceReasons: { 4: 'trabaja esta tarde', 12: 'había avisado por un compromiso familiar', 20: 'está enfermo', 15: 'tiene problemas de transporte' } },
    { id: 'thursday', day: 'Jueves', intensity: 'Alta', blocks: ['Táctica', 'Balón parado'], status: 'pending', planningStatus: 'UNPLANNED', attendance: 18, totalPlayers: players.length, absentPlayerIds: [2, 19], plannedAbsentPlayerIds: [2, 19], plannedAbsenceReasons: { 2: 'trabaja esta tarde', 19: 'había avisado por estudios' } },
  ], weekClosed: false }
}

export function startNextTrainingWeek(current: TrainingGameState, sourcePlayers: Player[]) {
  const closed = current.sessions.every((session) => session.status === 'completed') && !current.weekClosed ? closeTrainingWeek(current, sourcePlayers) : current
  const state = clone(closed)
  state.week += 1
  state.weekClosed = false
  state.sessions = state.sessions.map((session) => ({ ...session, status: 'pending', planningStatus: 'UNPLANNED', plannedTacticalPlan: undefined, quality: undefined, qualityLabel: undefined, result: undefined, absentPlayerIds: [...(session.plannedAbsentPlayerIds ?? session.absentPlayerIds)], availableStaffIds: undefined, staffAbsenceNotes: undefined }))
  return state
}

export const getPlayerHappiness = (state: TrainingPlayerState) => mean(Object.values(state.happiness))
export const getTeamAuthority = (state: TrainingGameState) => mean(Object.values(state.players).map((player) => player.managerAuthority))
export const getTeamFitness = (state: TrainingGameState) => mean(Object.values(state.players).map((player) => player.fitness))
export const getTeamFatigue = (state: TrainingGameState) => mean(Object.values(state.players).map((player) => player.fatigue))
export const getTeamHappiness = (state: TrainingGameState) => mean(Object.values(state.players).map(getPlayerHappiness))
export function getEffectiveAttribute(state: TrainingPlayerState, attribute: PlayerAttribute) { return Math.min(20, state.baseAttributes[attribute] + (state.attributes[attribute]?.bonus ?? 0)) }
export function getPhysicalCapacity(state: TrainingPlayerState) { return mean(PHYSICAL_ATTRIBUTES.map((attribute) => getEffectiveAttribute(state, attribute))) }
export function getResistanceFatigueMultiplier(resistance: number) { return resistance <= 5 ? 1.12 : resistance <= 10 ? 1.12 - (resistance - 5) * .024 : resistance <= 15 ? 1 - (resistance - 10) * .026 : .87 - (resistance - 15) * .024 }
export function getPhysicalPenalty(fitness: number, fatigue: number) { const fitnessPenalty = fitness >= 85 ? 0 : fitness >= 70 ? -.25 : fitness >= 55 ? -.75 : fitness >= 40 ? -1.5 : -2.5; const fatiguePenalty = fatigue < 30 ? 0 : fatigue < 50 ? -.25 : fatigue < 70 ? -.75 : fatigue < 85 ? -1.5 : -2.5; return fitnessPenalty + fatiguePenalty }
export function getEffectiveMatchAttributes(state: TrainingPlayerState) { const penalty = getPhysicalPenalty(state.fitness, state.fatigue); const conditioned = Object.fromEntries(Object.keys(state.baseAttributes).map((key) => { const attribute = key as PlayerAttribute; const physicalFactor = PHYSICAL_ATTRIBUTES.includes(attribute) ? 1 : attribute === 'intensidad' ? .5 : 0; return [attribute, clamp20(getEffectiveAttribute(state, attribute) + penalty * physicalFactor)] })) as TrainingPlayerState['baseAttributes']; return applyPhysicalIssueToAttributes(conditioned, state.currentIssue) }

function qualityLabel(value: number, attendance: number): TrainingQualityLabel { if (attendance < TRAINING_BALANCE.minimumAttendance) return 'De mínimos'; return value >= 85 ? 'Excelente' : value >= 70 ? 'Buena' : value >= 50 ? 'Correcta' : value >= 30 ? 'Floja' : 'Mala' }
export function calculateSessionQuality(state: TrainingGameState, attendance: number, availableStaff: StaffPerson[] = []) { if (attendance < TRAINING_BALANCE.minimumAttendance) return { value: 10, label: 'De mínimos' as const }; const attendanceScore = 55 + ((attendance - 13) / 7) * 45; const staffQuality = calculateTrainingStaffImpact(availableStaff).quality; const group = mean([getTeamHappiness(state), getTeamFitness(state), 100 - getTeamFatigue(state)]); const value = clamp100(attendanceScore * .35 + getTeamAuthority(state) * .3 + staffQuality * .2 + group * .15); return { value, label: qualityLabel(value, attendance) } }
function attributeState(player: TrainingPlayerState, attribute: PlayerAttribute): AttributeTrainingState { return player.attributes[attribute] ??= { bonus: 0, consolidation: 0, consecutiveWeeks: 0, trainedThisWeek: false, maintainedThisWeek: false, exposuresThisWeek: 0 } }

function processAttribute(state: TrainingGameState, player: Player, trainingPlayer: TrainingPlayerState, attribute: PlayerAttribute, intensity: TrainingIntensity, qualityMultiplier: number, complete = false) {
  const progress = attributeState(trainingPlayer, attribute); const base = trainingPlayer.baseAttributes[attribute]; if (base >= 20) return 0
  const exposureMultiplier = TRAINING_BALANCE.repetition[Math.min(progress.exposuresThisWeek, 3)]
  const range = complete ? TRAINING_BALANCE.completeGain : TRAINING_BALANCE.provisionalGain
  const raw = randomRange(state, range[0], range[1]) * (complete ? 1 : TRAINING_BALANCE.intensityProgress[intensity]) * qualityMultiplier * provisionalDifficulty(getEffectiveAttribute(trainingPlayer, attribute)) * randomRange(state, ...TRAINING_BALANCE.individualResponse) * exposureMultiplier
  const gain = Math.max(0, Math.min(raw, 20 - base - progress.bonus, TRAINING_BALANCE.maxBonus - progress.bonus)); progress.bonus += gain; progress.trainedThisWeek ||= !complete; progress.maintainedThisWeek ||= complete; progress.exposuresThisWeek += 1
  progress.consolidation += gain * TRAINING_BALANCE.consolidationScale * ageFactor(player.age) * consolidationDifficulty(base) * continuityFactor(progress.consecutiveWeeks + 1)
  return gain
}

function physicalSessionEffects(session: FunctionalTrainingSession, trainingPlayer: TrainingPlayerState) { const blocks = actualBlocks(session); const base = blocks[0] === 'Descanso' ? { fitness: -2, fatigue: -18 } : blocks[0] === 'Lúdico' ? { fitness: 0, fatigue: 0 } : blocks.every((block) => block === 'Táctica' || block === 'Balón parado') ? { fitness: 0, fatigue: blocks.reduce((sum, block) => sum + (block === 'Táctica' ? -4 : -3), 0) } : (() => { const balanced = TRAINING_BALANCE.physicalByIntensity[session.intensity]; const physical = blocks.includes('Físico'); return { fitness: balanced.fitness * (physical ? 1.4 : 1), fatigue: balanced.fatigue * (physical ? 1.3 : 1) * getResistanceFatigueMultiplier(getEffectiveAttribute(trainingPlayer, 'resistencia')) } })(); const issue = getPhysicalIssueEffects(trainingPlayer.currentIssue); if (!issue) return base; return { fitness: base.fitness > 0 ? base.fitness * issue.recoveryMultiplier : base.fitness, fatigue: base.fatigue < 0 ? base.fatigue * issue.recoveryMultiplier : base.fatigue + issue.perceivedFatigue } }
export function calculateInjuryRisk(player: TrainingPlayerState, intensity: TrainingIntensity, hasPhysical: boolean) { let risk = TRAINING_BALANCE.baseInjuryRisk * ({ Baja: .6, Media: 1, Alta: 1.7 }[intensity]); if (player.fatigue > 50) risk *= 1.5; if (player.fatigue > 70) risk *= 1.8; if (player.fitness < 70) risk *= 1.4; if (player.fitness < 50) risk *= 1.8; if (hasPhysical) risk *= 1.35; if (getPhysicalCapacity(player) < 9) risk *= 1.3; risk *= getPhysicalIssueEffects(player.currentIssue)?.injuryRiskMultiplier ?? 1; return risk }
export const injuryRiskLabel = (risk: number): 'Bajo' | 'Moderado' | 'Alto' => risk < .004 ? 'Bajo' : risk < .009 ? 'Moderado' : 'Alto'

function humanReaction(trainingPlayer: TrainingPlayerState, blocks: TrainingBlock[], intensity: TrainingIntensity, quality: TrainingQualityLabel, visibleGain: boolean, consolidation: boolean) { const personality = PERSONALITY_MODIFIERS[trainingPlayer.personality]; let satisfaction = quality === 'Excelente' ? 1.5 : quality === 'Buena' ? .75 : quality === 'Floja' ? -.75 : quality === 'Mala' ? -1.5 : quality === 'De mínimos' ? -5 : 0; let authority = intensity === 'Alta' ? 1 : 0; if (intensity === 'Alta') { satisfaction += personality.highIntensityPreference; authority += personality.highIntensityPreference * .5 } if (intensity === 'Baja') satisfaction += personality.lowIntensityPreference
  if (blocks.includes('Físico')) { satisfaction += personality.physicalTrainingPreference; authority += .35 + personality.physicalTrainingPreference * .3 } if (blocks.includes('Táctica') || blocks.includes('Balón parado')) { satisfaction += personality.tacticalTrainingPreference * .5; authority += .3 } if (blocks.includes('Lúdico')) { satisfaction += 2 + personality.funTrainingPreference; authority -= .5; trainingPlayer.happiness.teammates = clamp100(trainingPlayer.happiness.teammates + 3 + Math.max(0, personality.sociability)) } if (blocks.includes('Descanso')) { satisfaction += personality.restPreference; authority -= .5 } if (visibleGain) satisfaction += 1 + personality.personalImprovementSensitivity * .25; if (consolidation) satisfaction += 2 + personality.personalImprovementSensitivity * .5; if (quality === 'De mínimos') authority = -4
  trainingPlayer.happiness.training = clamp100(trainingPlayer.happiness.training + satisfaction); trainingPlayer.managerAuthority = clamp100(trainingPlayer.managerAuthority + authority)
}

function gainMemory(item: FamiliarityMemory, amount: number) { const recovery = item.current < item.historicalMax * .6 ? 1.5 : item.current < item.historicalMax ? 1.25 : 1; item.current = clamp100(item.current + amount * recovery); item.historicalMax = Math.max(item.historicalMax, item.current); item.trainedThisWeek = true }
function trainTacticalFamiliarity(familiarity: TacticalFamiliarityState, plan: TacticalPlan, blocks: TrainingBlock[], intensity: TrainingIntensity, multiplier: number, deMinimos: boolean) { if (deMinimos) return; const targetedIntensity = TRAINING_BALANCE.intensityTactical[intensity]; const gainInstruction = (key: string, amount: number, usesIntensity = true) => gainMemory(familiarity.instructions[key][planValue(plan, key)], amount * multiplier * (usesIntensity ? targetedIntensity : 1)); const all = (amount: number, usesIntensity = false) => instructionKeys.forEach((key) => gainInstruction(key, amount, usesIntensity)); gainMemory(familiarity.formations[plan.formation], .5 * multiplier)
  blocks.forEach((block) => { if (block === 'Ataque posicional') ['mentality', 'passingStyle', 'tempo'].forEach((key) => gainInstruction(key, 4)); if (block === 'Transición ofensiva') gainInstruction('afterRecovery', 7); if (block === 'Defensa posicional / Presión') ['pressingHeight', 'pressingIntensity'].forEach((key) => gainInstruction(key, 5)); if (block === 'Transición defensiva') gainInstruction('afterLoss', 7); if (block === 'Táctica') { all(3); gainMemory(familiarity.formations[plan.formation], 5 * multiplier) } if (block === 'Completo') { all(1); gainMemory(familiarity.formations[plan.formation], 2 * multiplier) } if (block === 'Balón parado') gainMemory(familiarity.setPieces, 8 * multiplier) })
}
export function calculateOverallFamiliarity(familiarity: TacticalFamiliarityState, plan: TacticalPlan) { const get = (key: string) => familiarity.instructions[key][planValue(plan, key)].current; const attack = mean(['mentality', 'passingStyle', 'tempo'].map(get)); const transitionAttack = get('afterRecovery'); const defense = mean(['pressingHeight', 'pressingIntensity'].map(get)); const transitionDefense = get('afterLoss'); return mean([attack, transitionAttack, defense, transitionDefense]) * .8 + familiarity.formations[plan.formation].current * .2 }

export function executeTrainingSession(current: TrainingGameState, sessionId: string, plan: TacticalPlan, sourcePlayers: Player[], staffMembers: StaffPerson[] = []) { const state = clone(current); const session = state.sessions.find((item) => item.id === sessionId); if (!session || session.status === 'completed') return state; const attendees = sourcePlayers.filter((player) => !session.absentPlayerIds.includes(player.id)); session.attendance = attendees.length; const availableStaff = staffMembers.filter((member) => session.availableStaffIds?.includes(member.id)); const quality = calculateSessionQuality(state, attendees.length, availableStaff); const multiplier = TRAINING_BALANCE.qualityMultipliers[quality.label]; const blocks = actualBlocks(session); let totalGain = 0; let highestRisk = 0
  attendees.forEach((player) => { const trainingPlayer = state.players[player.id]; let playerGain = 0; if (quality.label !== 'De mínimos') { blocks.forEach((block) => { if (block === 'Completo') { const relevant = [...new Set([player.primaryPosition, ...player.secondaryPositions].flatMap((position) => Object.keys(POSITION_RATING_WEIGHTS[POSITION_TO_RATING_PROFILE[position]]) as PlayerAttribute[]))]; for (let count = 0; count < Math.min(5, relevant.length); count++) playerGain += processAttribute(state, player, trainingPlayer, relevant[Math.floor(randomRange(state, 0, relevant.length))], session.intensity, multiplier, true) } else (TRAINABLE_ATTRIBUTES[block] ?? []).forEach((attribute) => { const goalkeeperSafeAttribute = player.primaryPosition === 'POR' && attribute === 'alcanceAereo' ? 'juegoAereoPortero' : attribute; playerGain += processAttribute(state, player, trainingPlayer, goalkeeperSafeAttribute, block === 'Táctica' || block === 'Balón parado' ? 'Media' : session.intensity, multiplier) }) }) } else { blocks.forEach((block) => (TRAINABLE_ATTRIBUTES[block] ?? []).forEach((attribute) => { const goalkeeperSafeAttribute = player.primaryPosition === 'POR' && attribute === 'alcanceAereo' ? 'juegoAereoPortero' : attribute; playerGain += processAttribute(state, player, trainingPlayer, goalkeeperSafeAttribute, session.intensity, multiplier) })) }
    totalGain += playerGain; const physical = quality.label === 'De mínimos' ? { fitness: -1, fatigue: 2 } : physicalSessionEffects(session, trainingPlayer); trainingPlayer.fitness = clamp100(trainingPlayer.fitness + physical.fitness * (.9 + getPhysicalCapacity(trainingPlayer) / 100)); trainingPlayer.fatigue = clamp100(trainingPlayer.fatigue + physical.fatigue); highestRisk = Math.max(highestRisk, calculateInjuryRisk(trainingPlayer, session.intensity, blocks.includes('Físico'))); trainingPlayer.currentIssue = applyTrainingLoadToIssue(trainingPlayer.currentIssue, session.intensity, blocks.includes('Físico')); humanReaction(trainingPlayer, blocks, session.intensity, quality.label, playerGain >= .5, false) })
  trainTacticalFamiliarity(state.familiarity, plan, blocks, session.intensity, multiplier, quality.label === 'De mínimos'); session.status = 'completed'; session.quality = quality.value; session.qualityLabel = quality.label; session.result = { quality: quality.value, qualityLabel: quality.label, tacticalPlan: clone(plan), attendees: attendees.map((player) => player.id), injuryRisk: injuryRiskLabel(highestRisk), effects: [`Estado físico: ${getConditionLabel(getTeamFitness(state))}`, `Carga: ${getFatigueLabel(getTeamFatigue(state))}`, `Familiaridad táctica: ${getFamiliarityLabel(calculateOverallFamiliarity(state.familiarity, plan))}`], highlights: [`${attendees.length} jugadores completaron la sesión.`, availableStaff.length ? `Ayudaron ${availableStaff.length} miembros del Staff disponibles.` : 'El entrenador dirigió la sesión solo.', totalGain > 0 ? 'La sesión dejó progresos provisionales en la plantilla.' : 'No hubo progreso deportivo provisional.'] }; return state
}

export function closeTrainingWeek(current: TrainingGameState, sourcePlayers: Player[]) { if (current.weekClosed || current.sessions.some((session) => session.status !== 'completed')) return current; const state = clone(current); let setPiecesTrained = state.familiarity.setPieces.trainedThisWeek
  sourcePlayers.forEach((player) => { const trainingPlayer = state.players[player.id]; Object.entries(trainingPlayer.attributes).forEach(([key, progress]) => { if (!progress) return; const attribute = key as PlayerAttribute; if (!progress.trainedThisWeek) { progress.bonus *= progress.maintainedThisWeek ? TRAINING_BALANCE.completeMaintenanceDecay : TRAINING_BALANCE.bonusDecay; progress.consecutiveWeeks = 0 } else progress.consecutiveWeeks += 1; while (progress.consolidation >= 100 && trainingPlayer.baseAttributes[attribute] < 20) { trainingPlayer.baseAttributes[attribute] += 1; progress.bonus = Math.max(0, progress.bonus - 1); progress.consolidation -= 100; humanReaction(trainingPlayer, [], 'Media', 'Correcta', false, true) } progress.bonus = Math.min(progress.bonus, 20 - trainingPlayer.baseAttributes[attribute]); progress.trainedThisWeek = false; progress.maintainedThisWeek = false; progress.exposuresThisWeek = 0 }) })
  Object.values(state.familiarity.instructions).flatMap(Object.values).forEach((item) => { if (!item.trainedThisWeek) item.current = Math.max(item.historicalMax * TRAINING_BALANCE.tacticalFloor, item.current - TRAINING_BALANCE.tacticalDecay); item.trainedThisWeek = false }); Object.values(state.familiarity.formations).forEach((item) => { if (!item.trainedThisWeek) item.current = Math.max(item.historicalMax * TRAINING_BALANCE.tacticalFloor, item.current - TRAINING_BALANCE.tacticalDecay); item.trainedThisWeek = false }); if (setPiecesTrained) state.familiarity.setPieceWeeksWithoutTraining = 0; else { state.familiarity.setPieceWeeksWithoutTraining += 1; if (state.familiarity.setPieceWeeksWithoutTraining >= 3) state.familiarity.setPieces.current = Math.max(state.familiarity.setPieces.historicalMax * TRAINING_BALANCE.tacticalFloor, state.familiarity.setPieces.current - 3) } state.familiarity.setPieces.trainedThisWeek = false; state.weekClosed = true; return state
}
