import { useState } from 'react'
import { PlayerDetail } from '../components/PlayerDetail'
import { players } from '../data/mockData'
import type { Player, TacticalPlan, TrainingBlock, TrainingIntensity } from '../domain/models'
import { FULL_SESSION_BLOCKS, TRAINING_BLOCKS, previewTraining } from '../domain/training'
import { calculateOverallFamiliarity, closeTrainingWeek, executeTrainingSession, getPlayerHappiness, getTeamAuthority, getTeamFatigue, getTeamFitness, getTeamHappiness } from '../domain/trainingEngine'
import type { FunctionalTrainingSession, TrainingGameState } from '../domain/trainingTypes'
import { getPlayerPositions } from '../domain/playerRatings'
import './TrainingScreen.css'

type Props = { tacticalPlan: TacticalPlan; trainingState: TrainingGameState; onTrainingStateChange: (state: TrainingGameState) => void; onBack: () => void; onOpenTactics: () => void }
const absenceReasons = ['Trabajo', 'Estudios', 'Motivos personales', 'Molestias']
const happinessLabel = (value: number) => value >= 72 ? 'Feliz' : value >= 58 ? 'Conforme' : 'Descontento'

function TrainingSummary({ state, plan }: { state: TrainingGameState; plan: TacticalPlan }) {
  const values = [['Familiaridad táctica', `${calculateOverallFamiliarity(state.familiarity, plan).toFixed(0)}%`], ['Balón parado', `${state.familiarity.setPieces.current.toFixed(0)}%`], ['Condición física', `${getTeamFitness(state).toFixed(0)}%`], ['Cansancio', `${getTeamFatigue(state).toFixed(0)}%`], ['Felicidad', happinessLabel(getTeamHappiness(state))], ['Autoridad', `${getTeamAuthority(state).toFixed(0)}%`]]
  return <section className="training-summary" aria-label="Estado general del equipo">{values.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
}

function TacticalTrainingSummary({ plan, onOpenTactics }: { plan: TacticalPlan; onOpenTactics: () => void }) {
  const [expanded, setExpanded] = useState(false)
  return <section className="training-tactics-summary"><div className="training-section-heading"><h3>Planteamiento actual</h3><button type="button" onClick={() => setExpanded((value) => !value)}>{expanded ? 'Ocultar detalles' : 'Ver detalles'}</button></div><p>{plan.formation} · {plan.mentality} · {plan.passingStyle} · Ritmo {plan.tempo.toLowerCase()} · {plan.afterRecovery}<br />Presión {plan.pressingHeight.toLowerCase()} · Intensidad {plan.pressingIntensity.toLowerCase()} · {plan.afterLoss}</p>{expanded && <div className="tactical-details"><strong>Formación: {plan.formation}</strong><div><h4>Con balón</h4><p>Mentalidad: {plan.mentality}<br />Estilo de pase: {plan.passingStyle}<br />Ritmo: {plan.tempo}<br />Tras recuperación: {plan.afterRecovery}</p></div><div><h4>Sin balón</h4><p>Altura de presión: {plan.pressingHeight}<br />Intensidad de presión: {plan.pressingIntensity}<br />Tras pérdida: {plan.afterLoss}</p></div><p>Perder tiempo: {plan.timeWasting} · Ser agresivos: {plan.aggression}</p><button type="button" onClick={onOpenTactics}>Ir a Tácticas</button></div>}</section>
}

function TrainingEffectsPreview({ session }: { session: FunctionalTrainingSession }) { const full = FULL_SESSION_BLOCKS.includes(session.blocks[0]); const preview = previewTraining(full ? [session.blocks[0]] : session.blocks, session.intensity); return <section className="training-effects"><h4>Efectos previstos</h4><dl>{preview.effects.map(([name, level]) => <div key={name}><dt>{name}</dt><dd>{level}</dd></div>)}</dl>{preview.attributes.length > 0 && <p><strong>Principalmente trabaja:</strong><br />{preview.attributes.join(' · ')}</p>}<p><strong>Familiaridad táctica:</strong><br />{preview.familiarity.length ? preview.familiarity.join(' · ') : 'Sin efecto'}</p><small>{preview.intensityNote}</small></section> }

function CompletedSession({ session }: { session: FunctionalTrainingSession }) { const result = session.result; return <article className="training-session-card completed-session"><header><div><span>{session.day}</span><h3>Entrenamiento realizado</h3></div><span className="session-status">Realizada</span></header><p><strong>Asistencia: {session.attendance} / {session.totalPlayers}</strong><br />Calidad: <strong>{session.qualityLabel}</strong> ({session.quality?.toFixed(0)}/100)<br />Riesgo de lesión: <strong>{result?.injuryRisk}</strong></p><p>{(FULL_SESSION_BLOCKS.includes(session.blocks[0]) ? [session.blocks[0]] : session.blocks).join(' + ')}<br />Intensidad: {session.intensity}</p><div className="session-results"><h4>Resultados</h4>{result?.effects.map((effect) => <p key={effect}>{effect}</p>)}</div><div className="session-highlights"><h4>Destacados</h4>{result?.highlights.map((highlight) => <p key={highlight}>{highlight}</p>)}{result && <small>Planteamiento entrenado: {result.tacticalPlan.formation} · {result.tacticalPlan.mentality}</small>}</div></article> }

function TrainingSessionCard({ session, plan, onChange, onExecute }: { session: FunctionalTrainingSession; plan: TacticalPlan; onChange: (next: FunctionalTrainingSession) => void; onExecute: () => void }) {
  const [showAbsences, setShowAbsences] = useState(false); if (session.status === 'completed') return <CompletedSession session={session} />
  const isFull = FULL_SESSION_BLOCKS.includes(session.blocks[0]); const setBlock = (index: 0 | 1, block: TrainingBlock) => onChange({ ...session, blocks: FULL_SESSION_BLOCKS.includes(block) ? [block, block] : index === 0 && isFull ? [block, 'Táctica'] : session.blocks.map((item, i) => i === index ? block : item) as [TrainingBlock, TrainingBlock] })
  return <article className="training-session-card"><header><div><span>Sesión {session.id === 'tuesday' ? '1' : '2'}</span><h3>{session.day}</h3></div><span className="session-status">Pendiente</span></header><fieldset><legend>Intensidad</legend><div className="training-segments">{(['Baja', 'Media', 'Alta'] as TrainingIntensity[]).map((level) => <button key={level} type="button" className={session.intensity === level ? 'is-selected' : ''} aria-pressed={session.intensity === level} onClick={() => onChange({ ...session, intensity: level })}>{level}</button>)}</div></fieldset><div className="training-block-selectors"><label>Bloque 1<select value={session.blocks[0]} onChange={(event) => setBlock(0, event.target.value as TrainingBlock)}>{TRAINING_BLOCKS.map((block) => <option key={block}>{block}</option>)}</select></label>{isFull ? <div className="full-session-notice"><strong>{session.blocks[0]}</strong><span>Ocupa los dos bloques de la sesión</span></div> : <label>Bloque 2<select value={session.blocks[1]} onChange={(event) => setBlock(1, event.target.value as TrainingBlock)}>{TRAINING_BLOCKS.map((block) => <option key={block}>{block}</option>)}</select></label>}</div><div className="attendance"><strong>Asistencia prevista: {session.attendance} / {session.totalPlayers}</strong>{session.absentPlayerIds.length > 0 && <><button type="button" onClick={() => setShowAbsences((value) => !value)}>{session.absentPlayerIds.length} ausencias previstas</button>{showAbsences && <ul>{session.absentPlayerIds.map((id, index) => <li key={id}>{players.find((player) => player.id === id)?.name} — {absenceReasons[index % absenceReasons.length]}</li>)}</ul>}</>}</div><TrainingEffectsPreview session={session} /><button className="execute-session-button" type="button" onClick={onExecute}>Realizar sesión con {plan.formation}</button></article>
}

function TrainingSquadTable({ state, onSelect }: { state: TrainingGameState; onSelect: (player: Player) => void }) { return <section className="training-squad"><h3>Estado individual de la plantilla</h3><div className="training-table-wrapper"><table><thead><tr><th>Pos</th><th>Nombre</th><th>Personalidad</th><th>Condición</th><th>Cansancio</th><th>Felicidad</th><th>Satisf. entreno</th><th>Autoridad</th><th>Estado</th></tr></thead><tbody>{players.map((player) => { const individual = state.players[player.id]; return <tr key={player.id}><td>{getPlayerPositions(player).join('/')}</td><td><button type="button" onClick={() => onSelect(player)}>{player.name}</button></td><td>{individual.personality}</td><td>{individual.fitness.toFixed(0)}%</td><td>{individual.fatigue.toFixed(0)}%</td><td>{happinessLabel(getPlayerHappiness(individual))}</td><td>{individual.happiness.training.toFixed(0)}%</td><td>{individual.authorityWithCoach.toFixed(0)}%</td><td>{individual.fatigue >= 70 ? 'Muy cargado' : individual.fatigue >= 55 ? 'Cargado' : 'Disponible'}</td></tr> })}</tbody></table></div></section> }

export function TrainingScreen({ tacticalPlan, trainingState, onTrainingStateChange, onBack, onOpenTactics }: Props) {
  const [selectedPlayer, setSelectedPlayer] = useState<Player | null>(null)
  const updateSession = (next: FunctionalTrainingSession) => onTrainingStateChange({ ...trainingState, sessions: trainingState.sessions.map((session) => session.id === next.id ? next : session) })
  const selectedState = selectedPlayer ? trainingState.players[selectedPlayer.id] : null
  const detailPlayer = selectedPlayer && selectedState ? { ...selectedPlayer, attributes: selectedState.baseAttributes, fitness: selectedState.fitness, happiness: getPlayerHappiness(selectedState), personality: selectedState.personality } : null
  const provisionalProgress = selectedState ? Object.fromEntries(Object.entries(selectedState.attributes).map(([key, value]) => [key, value?.bonus ?? 0])) : undefined
  const canClose = trainingState.sessions.every((session) => session.status === 'completed') && !trainingState.weekClosed
  return <section className="training-screen"><header className="screen-header training-header"><button className="screen-back-button" type="button" onClick={onBack}>← Panel del club</button><div><h2>Entrenamiento</h2><span>Semana {trainingState.week}</span></div></header><TrainingSummary state={trainingState} plan={tacticalPlan} /><TacticalTrainingSummary plan={tacticalPlan} onOpenTactics={onOpenTactics} /><section className="training-sessions" aria-label="Planificación semanal">{trainingState.sessions.map((session) => <TrainingSessionCard key={session.id} session={session} plan={tacticalPlan} onChange={updateSession} onExecute={() => onTrainingStateChange(executeTrainingSession(trainingState, session.id, tacticalPlan, players))} />)}</section>{canClose && <div className="close-week-panel"><div><strong>Las dos sesiones están realizadas.</strong><p>Al cerrar la semana se aplicarán decadencia, continuidad y consolidación permanente.</p></div><button type="button" onClick={() => onTrainingStateChange(closeTrainingWeek(trainingState, players))}>Cerrar semana de entrenamiento</button></div>}{trainingState.weekClosed && <p className="week-closed-notice">Semana procesada. Sus efectos no volverán a aplicarse.</p>}<TrainingSquadTable state={trainingState} onSelect={setSelectedPlayer} />{detailPlayer && <PlayerDetail player={detailPlayer} provisionalProgress={provisionalProgress} onClose={() => setSelectedPlayer(null)} />}</section>
}
