import type { CompetitionPortalData } from '../../domain/competitionPortal'
import { ClubLink, RecentForm } from './ClubLink'
type Props = { data: CompetitionPortalData; onOpenClub: (id: string) => void }

export function StandingsTable({ data, onOpenClub }: Props) {
  return <><div className="federation-section-heading"><h2>Clasificación</h2><p>{data.currentMatchday ? `Estado actual · Jornada ${data.currentMatchday}` : 'La liga todavía no ha comenzado'}</p></div><div className="federation-table-wrap"><table className="federation-table federation-standings" aria-label="Clasificación actual de liga"><thead><tr><th scope="col">P</th><th scope="col">Equipo</th><th scope="col">PTS</th>{['PJ', 'G', 'E', 'P', 'GF', 'GC', 'DG', 'Últimos'].map(label => <th className={`federation-stat${label === 'Últimos' ? ' federation-last' : ''}`} key={label} scope="col">{label}</th>)}</tr></thead><tbody>{data.standings.map(row => <tr key={row.teamId} className={row.teamId === 'fc-poblenou' ? 'is-user-club' : undefined}><td>{row.position}</td><th scope="row"><div className="federation-team-cell"><ClubLink data={data} clubId={row.teamId} onOpen={onOpenClub} />{row.teamId === 'fc-poblenou' && <small className="federation-your-club">Tu club</small>}</div></th><td className="federation-points">{row.points}</td>{[row.played, row.won, row.drawn, row.lost, row.goalsFor, row.goalsAgainst, row.goalDifference > 0 ? `+${row.goalDifference}` : row.goalDifference].map((value, index) => <td className="federation-stat" key={index}>{value}</td>)}<td className="federation-stat federation-last"><RecentForm form={row.recentForm} /></td></tr>)}</tbody></table></div><p className="federation-note">3 puntos por victoria · 1 por empate. G: victoria · E: empate · P: derrota.</p></>
}
export function ScorersTable({ data, onOpenClub }: Props) {
  return <><div className="federation-section-heading"><h2>Ranking de goleadores</h2><p>Goles de liga</p></div><div className="federation-table-wrap"><table className="federation-table federation-scorers" aria-label="Goleadores de liga"><thead><tr><th scope="col">P</th><th scope="col">Nombre</th><th scope="col">Equipo</th><th scope="col">Goles (P)</th><th scope="col" className="federation-scorer-stat">PJ</th><th scope="col" className="federation-scorer-stat">Goles/partido</th></tr></thead><tbody>{data.scorers.map(row => <tr key={row.playerId}><td>{row.position}</td><th scope="row">{row.playerName}</th><td><ClubLink data={data} clubId={row.teamId} onOpen={onOpenClub} /></td><td className="federation-points">{row.goals} <small>({row.penaltyGoals})</small></td><td className="federation-scorer-stat" title={row.played === undefined ? 'Participaciones individuales no registradas' : undefined}>{row.played ?? '—'}</td><td className="federation-scorer-stat">{row.goalsPerMatch?.toLocaleString('es-ES', { maximumFractionDigits: 2 }) ?? '—'}</td></tr>)}{!data.scorers.length && <tr><td colSpan={6} className="federation-empty">Todavía no hay goles de liga. El ranking se actualizará al disputar los partidos.</td></tr>}</tbody></table></div><p className="federation-note">Entre paréntesis, goles de penalti. —: participaciones individuales sin registrar.</p></>
}
export function SanctionsTable({ data, matchday, onOpenClub }: Props & { matchday: number }) {
  const sanctions = data.sanctionsForMatchday(matchday)
  return <><div className="federation-section-heading"><h2>Sanciones · Jornada {matchday}</h2><p>Partidos de suspensión pendientes en esta jornada</p></div><div className="federation-table-wrap"><table className="federation-table federation-sanctions" aria-label={`Sanciones de la jornada ${matchday}`}><thead><tr><th scope="col">Jugador</th><th scope="col">Equipo</th><th scope="col" className="federation-sanction-position">Posición</th><th scope="col">Sanción</th><th scope="col">Motivo</th></tr></thead><tbody>{sanctions.map(sanction => <tr key={sanction.id}><th scope="row">{data.playerNames.get(sanction.playerId) ?? 'Jugador no registrado'}</th><td><ClubLink data={data} clubId={sanction.teamId} onOpen={onOpenClub} /></td><td className="federation-sanction-position">{data.playerPositions.get(sanction.playerId) ?? '—'}</td><td><strong>{sanction.remainingMatches}</strong> {sanction.remainingMatches === 1 ? 'partido' : 'partidos'}</td><td>{sanction.reason}</td></tr>)}{!sanctions.length && <tr><td colSpan={5} className="federation-empty">No hay sanciones para esta jornada.</td></tr>}</tbody></table></div></>
}
